import React, { createContext, useContext, useState, useEffect } from 'react';
import { DEMO_USERS, TARGET_BUYERS } from '../constants/mockData';
import { CadastreDatabaseService } from '../services/databaseService';

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  // Load active user or fallback to first database persona (Rajesh Kumar)
  const [currentUser, setCurrentUser] = useState(() => {
    return CadastreDatabaseService.getActiveUser();
  });

  const [activeRoleView, setActiveRoleView] = useState(() => {
    const user = CadastreDatabaseService.getActiveUser();
    return user?.activeRole || 'OWNER';
  });

  // Global search input in top bar
  const [globalSearch, setGlobalSearch] = useState('');

  // All 100 Cadastral Parcels from Database
  const [allParcels, setAllParcels] = useState(() => {
    return CadastreDatabaseService.getParcels();
  });

  // All 100 Pending Transfers from Database
  const [transfers, setTransfers] = useState(() => {
    return CadastreDatabaseService.getTransfers();
  });

  // Cryptographic Sell tokens generated by citizen
  const [sellTokens, setSellTokens] = useState(() => {
    return CadastreDatabaseService.getSellTokens();
  });

  // Notification / toast feedback
  const [toast, setToast] = useState(null);

  useEffect(() => {
    CadastreDatabaseService.setActiveUser(currentUser);
    if (currentUser?.activeRole) {
      setActiveRoleView(currentUser.activeRole);
    }
  }, [currentUser]);

  useEffect(() => {
    CadastreDatabaseService.saveParcels(allParcels);
  }, [allParcels]);

  useEffect(() => {
    CadastreDatabaseService.saveTransfers(transfers);
  }, [transfers]);

  useEffect(() => {
    CadastreDatabaseService.saveSellTokens(sellTokens);
  }, [sellTokens]);

  const showToast = (message, type = 'success') => {
    setToast({ message, type, id: Date.now() });
    setTimeout(() => {
      setToast(null);
    }, 4500);
  };

  const login = (emailOrUsername, password, expectedRole = null) => {
    const demoUsers = CadastreDatabaseService.getDemoUsers();
    const found = demoUsers.find(
      (u) =>
        (u.email.toLowerCase() === emailOrUsername.toLowerCase() ||
         u.username.toLowerCase() === emailOrUsername.toLowerCase()) &&
        u.password === password
    );

    if (found) {
      const isUserRegistrar = found.role === 'REGISTRAR' || found.activeRole === 'REGISTRAR';
      
      // Strict Portal Segregation
      if (expectedRole === 'REGISTRAR' && !isUserRegistrar) {
        return {
          success: false,
          message: 'Access Denied: This is a Citizen account. Citizens are only permitted to sign in to the Citizen Landholder Portal.'
        };
      }

      if (expectedRole === 'CITIZEN' && isUserRegistrar) {
        return {
          success: false,
          message: 'Access Denied: This is a Sub-Registrar / Government Authority account. Registrars must sign in using the Registrar Gateway.'
        };
      }

      setCurrentUser(found);
      setActiveRoleView(found.activeRole || (isUserRegistrar ? 'REGISTRAR' : 'OWNER'));
      showToast(`Welcome back, ${found.name}!`, 'success');
      return { success: true, user: found };
    }
    return { success: false, message: 'Invalid credentials. Please verify your email and password, or select a demo account.' };
  };

  const signup = (newUserData) => {
    const demoUsers = CadastreDatabaseService.getDemoUsers();
    const existing = demoUsers.find(
      (u) =>
        u.email.toLowerCase() === newUserData.email.toLowerCase() ||
        (newUserData.username && u.username.toLowerCase() === newUserData.username.toLowerCase())
    );

    if (existing) {
      return { success: false, message: 'An account with this email already exists. Please sign in.' };
    }

    const isRegistrar = newUserData.role === 'REGISTRAR';

    const createdUser = {
      id: isRegistrar ? `REG-${Date.now().toString().slice(-4)}` : `USR-${Date.now().toString().slice(-4)}`,
      name: newUserData.name,
      email: newUserData.email,
      username: newUserData.username || newUserData.email.split('@')[0],
      password: newUserData.password,
      role: isRegistrar ? 'REGISTRAR' : 'CITIZEN',
      status: 'ACTIVE',
      activeRole: isRegistrar ? 'REGISTRAR' : (newUserData.activeRole || 'OWNER'),
      avatar: newUserData.avatar || (isRegistrar 
        ? 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80'
        : 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80'),
      wallet: `0x${Array.from({length: 40}, () => Math.floor(Math.random()*16).toString(16)).join('')}`,
      description: newUserData.description || (isRegistrar 
        ? `Sub-Registrar Officer • ${newUserData.jurisdiction || 'Tehsil Registry Office'}`
        : 'Registered Citizen Titleholder with Section 5 biometric identity'),
      jurisdiction: newUserData.jurisdiction || (isRegistrar ? 'Sub-Registrar Noida-I, UP' : 'Gautam Buddha Nagar / Noida, UP'),
      phone: newUserData.phone || '+91 98765 43210'
    };

    CadastreDatabaseService.registerUser(createdUser);
    setCurrentUser(createdUser);
    setActiveRoleView(createdUser.activeRole);
    showToast(`Account created successfully! Welcome, ${createdUser.name}`, 'success');
    return { success: true, user: createdUser };
  };

  const loginAsDemo = (demoUser) => {
    setCurrentUser(demoUser);
    setActiveRoleView(demoUser.activeRole || 'OWNER');
    showToast(`Logged in as ${demoUser.name} (${demoUser.activeRole})`, 'info');
  };

  const updateProfile = (updatedFields) => {
    setCurrentUser((prev) => {
      const updated = { ...prev, ...updatedFields };
      CadastreDatabaseService.setActiveUser(updated);
      return updated;
    });
    showToast('Profile information updated successfully', 'success');
  };

  const logout = () => {
    setCurrentUser(null);
    showToast('Signed out of Citizen Portal', 'info');
  };

  const resetDemoState = () => {
    CadastreDatabaseService.resetToDefaults();
    const freshUsers = CadastreDatabaseService.getDemoUsers();
    setCurrentUser(freshUsers[0]);
    setActiveRoleView('OWNER');
    setAllParcels(CadastreDatabaseService.getParcels());
    setTransfers(CadastreDatabaseService.getTransfers());
    setSellTokens([]);
    showToast('Cadastral database & session reset to initial state', 'warning');
  };

  // Dynamically compute user's parcels
  const userParcels = allParcels.filter((p) => {
    if (!currentUser) return false;
    const userName = currentUser.name?.toLowerCase();
    const isPrimary = p.currentOwner?.toLowerCase() === userName ||
                     p.primaryOwner?.toLowerCase() === userName;
    const isOwnerInList = (p.owners || []).some(
      (o) => o.name?.toLowerCase() === userName
    );
    return isPrimary || isOwnerInList;
  });

  // Dynamically compute user's nominee properties
  const userNomineeProperties = allParcels.filter((p) => {
    if (!currentUser) return false;
    return (p.nominees || []).some(
      (n) => n.name?.toLowerCase() === currentUser.name?.toLowerCase()
    );
  });

  // Dynamically compute user's transfers (both selling and buying)
  const userTransfers = transfers.filter((t) => {
    if (!currentUser) return false;
    const isSeller = t.seller?.toLowerCase() === currentUser.name?.toLowerCase();
    const isBuyer = t.buyer?.toLowerCase() === currentUser.name?.toLowerCase();
    return isSeller || isBuyer;
  });

  // Actions
  const generateSellToken = (parcelId, buyerId, buyerName) => {
    const newToken = {
      tokenId: `TK-${Math.floor(100000 + Math.random() * 900000)}`,
      parcelId,
      buyerId,
      buyerName,
      createdDate: new Date().toISOString(),
      expiresIn: '48 Hours',
      signature: `0x${Array.from({length: 32}, () => Math.floor(Math.random()*16).toString(16)).join('')}`,
      status: 'ACTIVE'
    };
    setSellTokens((prev) => [newToken, ...prev]);
    showToast(`Sell Token ${newToken.tokenId} issued for ${buyerName}`, 'success');
    return newToken;
  };

  const revokeSellToken = (tokenId) => {
    setSellTokens((prev) => prev.filter((t) => t.tokenId !== tokenId));
    showToast(`Sell Token ${tokenId} successfully revoked`, 'info');
  };

  const approveTransferPetition = (transferId) => {
    setTransfers((prev) =>
      prev.map((t) => {
        if (t.id === transferId) {
          return {
            ...t,
            status: 'AWAITING_REGISTRAR',
            stage: 'REGISTRAR_REVIEW',
            approvedAt: new Date().toISOString()
          };
        }
        return t;
      })
    );
    showToast(`Conveyance Petition ${transferId} approved with cryptographic signature`, 'success');
  };

  return (
    <AuthContext.Provider
      value={{
        currentUser,
        login,
        signup,
        loginAsDemo,
        logout,
        updateProfile,
        activeRoleView,
        setActiveRoleView,
        globalSearch,
        setGlobalSearch,
        allParcels,
        parcels: userParcels.length > 0 ? userParcels : allParcels.slice(0, 8),
        nomineeProperties: userNomineeProperties,
        transfers,
        userTransfers,
        sellTokens,
        generateSellToken,
        revokeSellToken,
        approveTransferPetition,
        resetDemoState,
        toast,
        showToast
      }}
    >
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}

export default AuthProvider;
