import React, { createContext, useContext, useState, useEffect } from 'react';
import { DEMO_USERS, INITIAL_PARCELS } from '../constants/mockData';
import { CadastreDatabaseService } from '../services/databaseService';

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  // Load saved user or default to first demo user
  const [currentUser, setCurrentUser] = useState(() => {
    return CadastreDatabaseService.getActiveUser();
  });

  const [activeRoleView, setActiveRoleView] = useState('OWNER'); // OWNER | BUYER | NOMINEE
  const [parcels, setParcels] = useState(() => {
    return CadastreDatabaseService.getParcels();
  });
  
  // Sell tokens generated by the citizen
  const [sellTokens, setSellTokens] = useState(() => {
    return CadastreDatabaseService.getSellTokens();
  });

  // Track notifications / banner alerts
  const [toast, setToast] = useState(null);

  useEffect(() => {
    CadastreDatabaseService.setActiveUser(currentUser);
  }, [currentUser]);

  useEffect(() => {
    CadastreDatabaseService.saveParcels(parcels);
  }, [parcels]);

  useEffect(() => {
    CadastreDatabaseService.saveSellTokens(sellTokens);
  }, [sellTokens]);

  const showToast = (message, type = 'success') => {
    setToast({ message, type, id: Date.now() });
    setTimeout(() => {
      setToast(null);
    }, 4500);
  };

  const login = (emailOrUsername, password) => {
    const found = DEMO_USERS.find(
      (u) =>
        (u.email.toLowerCase() === emailOrUsername.toLowerCase() ||
         u.username.toLowerCase() === emailOrUsername.toLowerCase()) &&
        u.password === password
    );

    if (found) {
      setCurrentUser(found);
      setActiveRoleView(found.activeRole || 'OWNER');
      showToast(`Welcome back, ${found.name}!`, 'success');
      return { success: true };
    }
    return { success: false, message: 'Invalid credentials. Please use demo fixtures below.' };
  };

  const loginAsDemo = (demoUser) => {
    setCurrentUser(demoUser);
    setActiveRoleView(demoUser.activeRole || 'OWNER');
    showToast(`Logged in as ${demoUser.name}`, 'info');
  };

  const logout = () => {
    setCurrentUser(null);
    showToast('Signed out of Citizen Portal', 'info');
  };

  const resetDemoState = () => {
    setParcels(INITIAL_PARCELS);
    setSellTokens([]);
    setCurrentUser(DEMO_USERS[0]);
    setActiveRoleView('OWNER');
    CadastreDatabaseService.resetToDefaults();
    showToast('Synthetic Demo State reset to default', 'warning');
  };

  const generateSellToken = (parcelId, buyerId, buyerName) => {
    const newToken = {
      tokenId: `TK-${Math.floor(100000 + Math.random() * 900000)}`,
      parcelId,
      buyerId,
      buyerName,
      createdDate: new Date().toISOString(),
      expiresIn: '48 Hours',
      signature: `0x7b...${Math.random().toString(16).substring(2, 8)}`,
      status: 'ACTIVE'
    };
    setSellTokens((prev) => [newToken, ...prev]);
    showToast(`Sell Token ${newToken.tokenId} generated for ${buyerName}`, 'success');
    return newToken;
  };

  const revokeSellToken = (tokenId) => {
    setSellTokens((prev) => prev.filter((t) => t.tokenId !== tokenId));
    showToast(`Sell Token ${tokenId} successfully revoked`, 'info');
  };

  return (
    <AuthContext.Provider
      value={{
        currentUser,
        login,
        loginAsDemo,
        logout,
        activeRoleView,
        setActiveRoleView,
        parcels,
        sellTokens,
        generateSellToken,
        revokeSellToken,
        resetDemoState,
        toast,
        showToast
      }}
    >
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
